# 1. pick a Node 16 image

# 2. set a working directory

# 3. declare all the environemnt variables needed

# 4. copy the app into the work directory

# 5. install all the packages needed for NodeJS

# 6. expose the port needed

# 7. start the app
