# 1. pick a Node 16 image
FROM node:16-alpine:latest

# 2. set a working directory
WORKDIR /app

# 3. declare all the environemnt variables needed
ENV DATABASE_HOST=localhost
ENV DATABASE_PORT=5432
ENV DATABASE_NAEM=user
ENV DATABASE_USERNAME=g0620_team1_hacker4
ENV DATABASE_PASSWORD=lloydsHack1!
ENV CONFIG_FILE_PATH=

# 4. copy the app into the work directory

# 5. install all the packages needed for NodeJS

# 6. expose the port needed

# 7. start the app
