# 1. pick a node 11.13.0-alpine image

# 2. create destination directory

# 3. update and install dependency

# 4. copy the app into the work directory and install packages needed for NodeJS

# 5. build necessary, even if no static files are needed,
# since it builds the server as well

# 6. expose the port on container

# 7. set app serving to permissive / assigned

# 8. set app port

# 9. start the app
